// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJeRze6rTFP71ZcumN15Lya0xzJtjzT0s',
    appId: '1:136833260643:web:ae1f5c3e76ae44bbba2c56',
    messagingSenderId: '136833260643',
    projectId: 'flutter-workout-routine',
    authDomain: 'flutter-workout-routine.firebaseapp.com',
    databaseURL: 'https://flutter-workout-routine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-workout-routine.appspot.com',
    measurementId: 'G-3MFWR9CYH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDabTQWBo7dkYHIog0uVn4d6-mWGG_JcyQ',
    appId: '1:136833260643:android:b1af3fc579b1ff07ba2c56',
    messagingSenderId: '136833260643',
    projectId: 'flutter-workout-routine',
    databaseURL: 'https://flutter-workout-routine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-workout-routine.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN4XdfwDMDSNKVXLqNpxRRu9wJ-i9MHIU',
    appId: '1:136833260643:ios:bd7bd2587e95c0a7ba2c56',
    messagingSenderId: '136833260643',
    projectId: 'flutter-workout-routine',
    databaseURL: 'https://flutter-workout-routine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-workout-routine.appspot.com',
    iosBundleId: 'me.faustojc.workoutRoutine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN4XdfwDMDSNKVXLqNpxRRu9wJ-i9MHIU',
    appId: '1:136833260643:ios:135ffff07dd64096ba2c56',
    messagingSenderId: '136833260643',
    projectId: 'flutter-workout-routine',
    databaseURL: 'https://flutter-workout-routine-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-workout-routine.appspot.com',
    iosBundleId: 'me.faustojc.workoutRoutine.RunnerTests',
  );
}
